# SPDX-License-Identifier: GPL-2.0
%YAML 1.2
---
$id: "http://kernel.org/schemas/netlink/schema.yaml#"
$schema: "http://kernel.org/meta-schemas/core.yaml#"

title: Protocol
description: Specification of a genetlink protocol
type: object
required: [ name, description, attribute-sets, operations ]
additionalProperties: False
properties:
  name:
    description: Name of the genetlink family.
    type: string
  description:
    type: string
  version:
    description: Generic Netlink family version. Default is 1.
    type: integer
  protocol:
    description: Schema compatibility level. Default is "genetlink".
    enum: [ genetlink, genetlink-c, genetlink-legacy, netlink-raw ] # Trim
  # Start genetlink-c
  uapi-header:
    description: Path to the uAPI header, default is linux/${family-name}.h
    type: string
  attr-cnt-suffix:
    description: Suffix for last member of attribute enum, default is "MAX".
    type: string
  # End genetlink-c

  definitions:
    description: Array of type and constant definitions.
    type: array
    items:
      type: object
      required: [ type, name ]
      additionalProperties: False
      properties:
        name:
          type: string
        header:
          description: For C-compatible languages, header which already defines this value.
          type: string
        type:
          enum: [ const, enum, flags, struct ] # Trim
        # For const
        value:
          description: For const - the value.
          oneOf: [ { type: string }, { type: integer }]
        # For enum and flags
        value-start:
          description: For enum or flags the literal initializer for the first value.
          oneOf: [ { type: string }, { type: integer }]
        entries:
          description: For enum or flags array of values
          type: array
          items:
            type: string
        # Start genetlink-c
        value-prefix:
          description: For enum the prefix of the values, optional.
          type: string
        # End genetlink-c
        # Start genetlink-legacy
        members:
          description: List of struct members. Only scalars and strings members allowed.
          type: array
          items:
            type: object
            required: [ name, type ]
            additionalProperties: False
            properties:
              name:
                type: string
              type:
                enum: [ u8, u16, u32, u64, s8, s16, s32, s64, nul-string ]
              len:
                oneOf: [ { type: string }, { type: integer }]
        # End genetlink-legacy

  attribute-sets:
    description: Definition of attribute spaces for this family.
    type: array
    items:
      description: Definition of a single attribute space.
      type: object
      required: [ name, attributes ]
      additionalProperties: False
      properties:
        name:
          description: |
            Name used when referring to this space in other definitions, not used outside of YAML.
          type: string
        # Strictly speaking 'name-prefix' and 'subset-of' should be mutually exclusive.
        name-prefix:
          description: |
            Prefix for the C enum name of the attributes. Default family[name]-set[name]-a-
          type: string
        name-enum:
          description: Name for the enum type of the attribute.
          type: string
        description:
          description: Documentation of the space.
          type: string
        subset-of:
          description: |
            Name of another space which this is a logical part of. Sub-spaces can be used to define
            a limited group of attributes which are used in a nest.
          type: string
        attributes:
          description: List of attributes in the space.
          type: array
          items:
            type: object
            required: [ name, type ]
            additionalProperties: False
            properties:
              name:
                type: string
              type: &attr-type
                enum: [ unused, flag, binary, u8, u16, u32, u64, s32, s64,
                        nul-string, multi-attr, nest, array-nest, nest-type-value ]
              description:
                description: Documentation of the attribute.
                type: string
              value:
                description: Value for the enum item representing this attribute in the uAPI.
                type: integer
              type-value:
                description: Name of the value extracted from the type of a nest-type-value attribute.
                type: array
                items:
                  type: string
              len:
                oneOf: [ { type: string }, { type: integer }]
              sub-type: *attr-type
              nested-attributes:
                description: Name of the space (sub-space) used inside the attribute.
                type: string
              enum:
                description: Name of the enum type used for the atttribute.
                type: string
              flags-mask:
                description: Name of the flags constant on which to base mask (unsigned scalar types only).
                type: string
  operations:
    description: Operations supported by the protocol.
    type: object
    required: [ list ]
    additionalProperties: False
    properties:
      enum-model:
        description: |
          The model of assigning values to the operations.
          "unified" is the recommended model where all message types belong
          to a single enum.
          "directional" has the messages sent to the kernel and from the kernel
          enumerated separately.
          "notify-split" has the notifications and request-response types in
          different enums.
        enum: [ unified, directional, notify-split ]
      name-prefix:
        description: |
          Prefix for the C enum name of the command. The name is formed by concatenating
          the prefix with the upper case name of the command, with dashes replaced by underscores.
        type: string
      name-enum:
        description: Name for the enum type with commands.
        type: string
      async-prefix:
        description: Same as name-prefix but used to render notifications and events to separate enum.
        type: string
      async-enum:
        description: Name for the enum type with notifications/events.
        type: string
      list:
        description: List of commands
        type: array
        items:
          type: object
          additionalProperties: False
          required: [ name, description ]
          properties:
            name:
              description: Name of the operation, also defining its C enum value in uAPI.
              type: string
            description:
              description: Documentation for the command.
              type: string
            value:
              description: Value for the enum in the uAPI.
              type: integer
            attribute-set:
              description: |
                Attribute space from which attributes directly in the requests and replies
                to this command are defined.
              type: string
            flags: &cmd_flags
              description: Command flags.
              type: array
              items:
                enum: [ admin-perm ]
            dont-validate:
              description: Kernel attribute validation flags.
              type: array
              items:
                enum: [ strict, dump ]
            do: &subop-type
              description: Main command handler.
              type: object
              additionalProperties: False
              properties:
                request: &subop-attr-list
                  description: Definition of the request message for a given command.
                  type: object
                  additionalProperties: False
                  properties:
                    attributes:
                      description: |
                        Names of attributes from the attribute-set (not full attribute
                        definitions, just names).
                      type: array
                      items:
                        type: string
                reply: *subop-attr-list
            dump: *subop-type
            notify:
              description: Name of the command sharing the reply type with this notification.
              type: string
            event:
              description: Explicit list of the attributes for the notification.
              type: array
              items:
                type: string
            mcgrp:
              description: Name of the multicast group generating given notification.
              type: string
  mcast-groups:
    description: List of multicast groups.
    type: object
    required: [ name-prefix, list ]
    additionalProperties: False
    properties:
      name-prefix:
        description: Name prefix for the define associated with the group.
        type: string
      name-suffix:
        description: |
          Name suffix for the define associated with the group. Multicast group defines seem to be unique
          in having a name-prefix as well as suffix.
        type: string
      list:
        description: List of groups.
        type: array
        items:
          type: object
          required: [ name ]
          additionalProperties: False
          properties:
            name:
              description: |
                The name for the group, used to form the define and the value of the define, unless value
                is specified separately.
              type: string
            value:
              description: String value for the define and group name.
              type: string
            flags: *cmd_flags
